[package]
name = "chapter3"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
bevy_procedural_tilemaps = "0.1.3"
bevy_common_assets = { version = "0.14", features = ["ron"] }
serde = { version = "1.0", features = ["derive"] }